version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: docrepo_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-document_repository}
      POSTGRES_USER: ${POSTGRES_USER:-docrepo_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_this}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database_setup.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - docrepo_network_dev

  # Backend API (Development with hot reload)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: docrepo_backend_dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-docrepo_user}:${POSTGRES_PASSWORD:-secure_password_change_this}@postgres:5432/${POSTGRES_DB:-document_repository}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-not-for-production}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-720}  # Longer for dev
      UPLOAD_DIRECTORY: /app/uploads
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      HOST: 0.0.0.0
      PORT: 8088
    ports:
      - "8088:8088"
    volumes:
      - ./backend:/app
      - backend_uploads_dev:/app/uploads
    depends_on:
      - postgres
    networks:
      - docrepo_network_dev
    command: ["uvicorn", "main_production_fast:app", "--host", "0.0.0.0", "--port", "8088", "--reload"]

  # Frontend (Development with hot reload)
  frontend:
    image: node:18-alpine
    container_name: docrepo_frontend_dev
    restart: unless-stopped
    working_dir: /app
    environment:
      REACT_APP_API_URL: http://localhost:8088
      REACT_APP_DOCEX_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - docrepo_network_dev
    command: ["sh", "-c", "npm install && npm start"]

volumes:
  postgres_data_dev:
    driver: local
  backend_uploads_dev:
    driver: local

networks:
  docrepo_network_dev:
    driver: bridge
